#Thanks to ChatGPT and Naspa Cheat Sheet for word list  and W3schools for hex converter 
import streamlit as st
import random
import string
import json
import base64

import numpy as np

# pip install streamlit-local-storage
from streamlit_local_storage import LocalStorage

three_letter_words = np.array("""
AAH AAL AAS ABA ABS ABY ACE ACK ACT ADD ADO ADS ADZ AFF AFT
AGA AGE AGO AGS AHA AHI AHS AID AIL AIM AIN AIR AIS AIT AJI
ALA ALB ALE ALL ALP ALS ALT AMA AMI AMP AMU ANA AND ANE ANI
ANT ANY APE APO APP APT ARB ARC ARE ARF ARK ARM ARO ARS ART
ASH ASK ASP ASS ATE ATS ATT AUK AVA AVE AVO AWA AWE AWL AWN
AXE AYE AYS AZO BAA BAD BAE BAG BAH BAL BAM BAN BAP BAR BAS
BAT BAY BED BEE BEG BEL BEN BES BET BEY BIB BID BIG BIN BIO
BIS BIT BIZ BOA BOB BOD BOG BOO BOP BOS BOT BOW BOX BOY BRA
BRO BRR BUB BUD BUG BUM BUN BUR BUS BUT BUY BYE BYS CAB CAD
CAF CAL CAM CAN CAP CAR CAT CAW CAY CEE CEL CEP CHI CIG CIS
COB COD COG COL CON COO COP COR COS COT COW COX COY COZ CRU
CRY CUB CUD CUE CUM CUP CUR CUT CUZ CWM DAB DAD DAG DAH DAK
DAL DAM DAN DAP DAS DAW DAY DEB DEE DEF DEL DEN DEP DEV DEW
DEX DEY DIB DID DIE DIF DIG DIM DIN DIP DIS DIT DOC DOE DOG
DOH DOL DOM DON DOR DOS DOT DOW DOX DRY DUB DUD DUE DUG DUH
DUI DUM DUN DUO DUP DYE EAR EAT EAU EBB ECO ECU EDH EDS EEK
EEL EEW EFF EFS EFT EGG EGO EKE ELD ELF ELK ELL ELM ELS EME
EMO EMS EMU END ENG ENS EON ERA ERE ERG ERN ERR ERS ESS EST
ETA ETH EVE EWE EYE FAB FAD FAG FAH FAM FAN FAR FAS FAT FAV
FAX FAY FED FEE FEH FEM FEN FER FES FET FEU FEW FEY FEZ FIB
FID FIE FIG FIL FIN FIR FIT FIX FIZ FLU FLY FOB FOE FOG FOH
FON FOO FOP FOR FOU FOX FOY FRO FRY FUB FUD FUG FUN FUR GAB
GAD GAE GAG GAL GAM GAN GAP GAR GAS GAT GAY GED GEE GEL GEM
GEN GET GEY GHI GIB GID GIE GIF GIG GIN GIP GIS GIT GNU GOA
GOB GOD GOO GOR GOS GOT GOX GOY GRR GUL GUM GUN GUT GUV GUY
GYM GYP HAD HAE HAG HAH HAJ HAM HAO HAP HAS HAT HAW HAY HEH
HEM HEN HEP HER HES HET HEW HEX HEY HIC HID HIE HIM HIN HIP
HIS HIT HMM HOB HOD HOE HOG HOM HON HOO HOP HOS HOT HOW HOY
HUB HUE HUG HUH HUM HUN HUP HUT HYP ICE ICH ICK ICY IDS IFF
IFS IGG ILK ILL IMP INK INN INS ION IRE IRK ISM ITS IVY JAB
JAG JAM JAR JAW JAY JEE JET JEU JIB JIG JIN JOB JOE JOG JOT
JOW JOY JUG JUN JUS JUT KAB KAE KAF KAS KAT KAY KEA KEF KEG
KEN KEP KEX KEY KHI KID KIF KIN KIP KIR KIS KIT KOA KOB KOI
KOP KOR KOS KUE KYE LAB LAC LAD LAG LAH LAM LAP LAR LAS LAT
LAV LAW LAX LAY LEA LED LEE LEG LEI LEK LET LEU LEV LEX LEY
LIB LID LIE LIN LIP LIS LIT LOB LOC LOG LOO LOP LOR LOT LOW
LOX LUD LUG LUM LUN LUV LUX LYE MAC MAD MAE MAG MAM MAN MAP
MAR MAS MAT MAW MAX MAY MED MEG MEH MEL MEM MEN MES MET MEW
MHO MIB MIC MID MIG MIL MIM MIR MIS MIX MMM MOA MOB MOC MOD
MOG MOI MOL MOM MON MOO MOP MOR MOS MOT MOW MUD MUG MUM MUN
MUS MUT MUX MYC NAB NAE NAG NAH NAM NAN NAP NAV NAW NAY NEB
NEE NEG NET NEW NIB NIL NIM NIP NIT NIX NOB NOD NOG NOH NOM
NOO NOR NOS NOT NOW NTH NUB NUG NUN NUS NUT OAF OAK OAR OAT
OBA OBE OBI OCA OCH ODA ODD ODE ODS OES OFF OFT OHM OHO OHS
OIK OIL OKA OKE OLD OLE OMA OMS ONE ONO ONS OOF OOH OOT OPA
OPE OPS OPT ORA ORB ORC ORE ORG ORS ORT OSE OUD OUR OUT OVA
OWE OWL OWN OWT OXO OXY PAC PAD PAH PAK PAL PAM PAN PAP PAR
PAS PAT PAW PAX PAY PEA PEC PED PEE PEG PEH PEN PEP PER PES
PET PEW PHI PHO PHT PIA PIC PIE PIG PIN PIP PIS PIT PIU PIX
PLY POD POH POI POL POM POO POP POS POT POW POX PRO PRY PSI
PST PUB PUD PUG PUL PUN PUP PUR PUS PUT PWN PYA PYE PYX QAT
QIS QUA RAD RAG RAH RAI RAJ RAM RAN RAP RAS RAT RAW RAX RAY
REB REC RED REE REF REG REI REM REP RES RET REV REX REZ RHO
RIA RIB RID RIF RIG RIM RIN RIP ROB ROC ROD ROE ROM ROO ROT
ROW RUB RUE RUG RUM RUN RUT RYA RYE RYU SAB SAC SAD SAE SAG
SAL SAN SAP SAT SAU SAW SAX SAY SEA SEC SEE SEG SEI SEL SEN
SER SET SEV SEW SEX SEZ SHA SHE SHH SHO SHY SIB SIC SIG SIM
SIN SIP SIR SIS SIT SIX SKA SKI SKY SLY SOB SOC SOD SOH SOL
SOM SON SOP SOS SOT SOU SOW SOX SOY SPA SPY SRI STY SUB SUE
SUK SUM SUN SUP SUQ SUS SYN TAB TAD TAE TAG TAJ TAM TAN TAO
TAP TAR TAS TAT TAU TAV TAW TAX TEA TEC TED TEE TEG TEL TEN
TES TET TEW THE THO THY TIC TIE TIL TIN TIP TIS TIT TIX TIZ
TOD TOE TOG TOM TON TOO TOP TOR TOT TOW TOY TRY TSK TUB TUG
TUI TUM TUN TUP TUT TUX TWA TWO TYE UDO UGH UKE ULU UMM UMP
UMS UNI UNS UPO UPS URB URD URN URP USE UTA UTE UTS VAC VAN
VAR VAS VAT VAU VAV VAW VAX VEE VEG VET VEX VIA VID VIE VIG
VIM VIN VIS VOE VOG VOW VOX VUG VUM WAB WAD WAE WAG WAN WAP
WAR WAS WAT WAW WAX WAY WEB WED WEE WEN WET WHA WHO WHY WIG
WIN WIS WIT WIZ WOE WOK WON WOO WOS WOT WOW WRY WUD WUZ WYE
WYN XED XIS YAG YAH YAK YAM YAP YAR YAS YAW YAY YEA YEH YEN
YEP YER YES YET YEW YEZ YIN YIP YOB YOD YOK YOM YON YOU YOW
YUK YUM YUP ZAG ZAP ZAS ZAX ZED ZEE ZEK ZEN ZEP ZIG ZIN ZIP
ZIT ZOA ZOO ZUZ ZZZ
""".split())

bingoes = np.array("""
ENTASIA
TAENIAS
BANTIES
BASINET
ACETINS
CINEAST
DESTAIN
DETAINS
INSTEAD
NIDATES
SAINTED
SATINED
STAINED
ETESIAN
FAINEST
EASTING
EATINGS
GENISTA
INGATES
INGESTA
SEATING
TAGINES
TEASING
SHEITAN
STHENIA
ISATINE
TAJINES
INTAKES
ELASTIN
ENTAILS
NAILSET
SALIENT
SALTINE
SLAINTE
TENAILS
ETAMINS
INMATES
TAMEINS
INANEST
STANINE
ATONIES
PANTIES
PATINES
SAPIENT
SPINATE
ANESTRI
ANTSIER
NASTIER
RATINES
RETAINS
RETINAS
RETSINA
STAINER
STEARIN
ENTASIS
NASTIES
SEITANS
SESTINA
TANSIES
TISANES
INSTATE
SATINET
AUNTIES
SINUATE
NAIVEST
NATIVES
VAINEST
TAWNIES
WANIEST
ANTISEX
SEXTAIN
ZANIEST
ZEATINS
ARISTAE
ASTERIA
ATRESIA
BAITERS
BARITES
REBAITS
TERBIAS
ATRESIC
CRISTAE
RACIEST
STEARIC
ARIDEST
ASTRIDE
DIASTER
DISRATE
STAIDER
TARDIES
TIRADES
AERIEST
SERIATE
FAIREST
AIGRETS
GAITERS
SEAGIRT
STAGIER
TRIAGES
HASTIER
AIRIEST
REALIST
RETAILS
SALTIER
SALTIRE
SLATIER
TAILERS
IMARETS
MAESTRI
MISRATE
SMARTIE
ANESTRI
ANTSIER
NASTIER
RATINES
RETAINS
RETINAS
RETSINA
STAINER
STEARIN
PARTIES
PASTIER
PIASTER
PIASTRE
PIRATES
PRATIES
TRAIPSE
ARTSIER
TARRIES
TARSIER
ARTSIES
SATIRES
ARTIEST
ARTISTE
ATTIRES
IRATEST
RATITES
STRIATE
TASTIER
RAVIEST
VASTIER
VERITAS
WAISTER
WAITERS
WARIEST
WASTRIE
CERATIN
CERTAIN
CREATIN
TACRINE
ANTIRED
DETRAIN
TRAINED
ARENITE
RETINAE
TRAINEE
FAINTER
GRANITE
GRATINE
INGRATE
TANGIER
TEARING
HAIRNET
INEARTH
THERIAN
INERTIA
KERATIN
LATRINE
RATLINE
RELIANT
RETINAL
TRENAIL
MINARET
RAIMENT
ENTRAIN
TRANNIE
PAINTER
PERTAIN
REPAINT
RETRAIN
TERRAIN
TRAINER
ANESTRI
ANTSIER
NASTIER
RATINES
RETAINS
RETINAS
RETSINA
STAINER
STEARIN
INTREAT
ITERANT
NATTIER
NITRATE
TERTIAN
RUINATE
TAURINE
URANITE
URINATE
TAWNIER
TINWARE
ACONITE
AEOLIAN
AERADIO
AEROSAT
AGONIES
AGONISE
AILERON
AIRDATE
AIRLINE
ALEURON
ALIENED
ALIENER
ALIENOR
ALINERS
ALUNITE
AMNIOTE
ANEROID
ANISEED
ANISOLE
ANODISE
ARANEID
ARENOSE
ARENOUS
ARIETTE
AROINTS
ATELIER
ATONERS
AUDIENT
AUDITEE
DARIOLE
DEARIES
DELAINE
DELATOR
DENARII
DIATRON
DILATER
DINEROS
DIORITE
DONATES
DOURINE
EARNEST
EASTERN
EDITION
EDITORS
ELATION
ELOINER
ELUTION
ENATION
ENTERAL
ENTIRES
ENTOILS
ENTRIES
ERASION
EROTICA
ESTRIOL
ETALONS
ETERNAL
GENITOR
GOATIER
GODETIA
IDEATES
INDORSE
INEDITA
INOSITE
IODATES
IONISER
IRONIES
IRONISE
ISOLATE
ISOLEAD
ITERATE
LADRONE
LEADIER
LENTOID
LEOTARD
LINEATE
LOANERS
LOITERS
MORAINE
NAILERS
NEAREST
NEGATOR
NEROLIS
NEUROID
NIOBATE
NITERIE
NOISIER
NORITES
OESTRIN
OLESTRA
ONLIEST
ORATION
ORDINES
ORIENTS
OUTDARE
OUTEARN
OUTLIER
OUTLINE
OUTREAD
OUTRIDE
RADIATE
RADIOES
RAINOUT
RANDIES
RATIONS
READIES
READOUT
REALISE
REDTAIL
REGINAE
RELOANS
RENAILS
RETINES
RETINOL
RETINUE
REUNITE
ROADIES
ROASTED
ROMAINE
RONDEAU
ROSEATE
ROSINED
ROUTINE
SANDIER
SANTERO
SARDINE
SENARII
SENATOR
SORDINE
SORTIED
SOUTANE
STERANE
STEROID
STONIER
STORIED
STOURIE
TAENIAE
TALONED
TELERAN
TIARAED
TOADIES
TOENAIL
TOILERS
TOLANES
TORSADE
TORULAE
TRAILED
TREASON
TRIALED
TRIENES
TRIODES
UNAIRED
URALITE
URANIDE
URINOSE
UTERINE
""".split())
two_letter_words = np.array("""
AA AB AD AE AG AH AI AL AM AN AR AS AT AW AX AY
BA BE BI BO BY
DA DE DO
ED EF EH EL EM EN ER ES ET EW EX
FA FE
GI GO
HA HE HI HM HO
ID IF IN IS IT
JO
KA KI
LA LI LO
MA ME MI MM MO MU MY
NA NE NO NU
OD OE OF OH OI OK OM ON OP OR OS OW OX OY
PA PE PI PO
QI
RE
SH SI SO
TA TE TI TO
UH UM UN UP US UT
WE WO
XI XU
YA YE YO
ZA
""".split())

# fill these in later :)
no_s_words = np.array(["AE", "AM", "AN", "AW","AX", "DE", "EH", "ET", "EW","EX", "HM", "IS", "JO","LO", "MM", "MY", "NA","NE", "OF", "OI", "OK","OS", "OW", "OX", "OY","SH", "TO", "UH", "US", "WE", "XU", "YO"])

# Full valid 4-letter word list (global, used across pages)
four_letter_words = """
    ARIE AROS BAES BRUH CATH COPI CRIA CRIP CUCK DOXX FAMs FAVS FOLX GANK GOYS GUAC HAOS HOSS JEDI KORI LARP LEWK LOCS MANI MARG MILF MPOX NARE NOOB OPPO PEDI PHEO PUBE PWNS RABI ROID SPAZ STAN STIM TWAT VAXX WELP YAJE YEET ZENS ZUKE
AAHS AALS ABAS ABBA ABBE ABED ABET ABLE ABLY ABOS ABRI ABUT ABYE ABYS ACAI ACED ACES ACHE ACHY ACID ACME ACNE ACRE ACRO ACTA ACTS ACYL ADDS ADIT ADOS ADZE AEON AERO AERY AFAR AFRO AGAR AGAS AGED AGEE AGER AGES AGHA AGIN AGIO AGLU AGLY AGMA AGOG AGON AGRO AGUE AHED AHEM AHIS AHOY AIDE AIDS AILS AIMS AINS AIRN AIRS AIRT AIRY AITS AJAR AJEE AJIS AKEE AKIN ALAE ALAN ALAR ALAS ALBA ALBS ALEC ALEE ALEF ALES ALFA ALGA ALIF ALIT ALKY ALLS ALLY ALMA ALME ALMS ALOE ALOW ALPS ALSO ALTO ALTS ALUM AMAH AMAS AMBO AMEN AMIA AMID AMIE AMIN AMIR AMIS AMMO AMOK AMPS AMUS AMYL ANAL ANAS ANDS ANES ANEW ANGA ANIL ANIS ANKH ANNA ANOA ANON ANSA ANTA ANTE ANTI ANTS ANUS APED APER APES APEX APOD APOS APPS APSE AQUA ARAK ARBS ARCH ARCO ARCS AREA AREG ARES ARFS ARGH ARIA ARID ARIL ARKS ARMS ARMY ARSE ARTS ARTY ARUM ARVO ARYL ASCI ASEA ASHY ASKS ASPS ATAP ATES ATMA ATOM ATOP AUGH AUKS AULD AUNT AURA AUTO AVER AVES AVID AVOS AVOW AWAY AWED AWEE AWES AWLS AWNS AWNY AWOL AWRY AXAL AXED AXEL AXES AXIL AXIS AXLE AXON AYAH AYES AYIN AZAN AZON BAAL BAAS BABA BABE BABU BABY BACH BACK BADE BADS BAFF BAGS BAHT BAIL BAIT BAKE BALD BALE BALK BALL BALM BALS BAMS BANC BAND BANE BANG BANI BANK BANS BAPS BARB BARD BARE BARF BARK BARM BARN BARS BASE BASH BASK BASS BAST BATE BATH BATS BATT BAUD BAWD BAWK BAWL BAWN BAYS BAZZ BEAD BEAK BEAL BEAM BEAN BEAR BEAT BEAU BECK BEDS BEDU BEEF BEEN BEEP BEER BEES BEET BEGS BELL BELS BELT BEMA BEND BENE BENS BENT BERG BERK BERM BEST BETA BETH BETS BEVY BEYS BHUT BIAS BIBB BIBE BIBS BICE BIDE BIDI BIDS BIER BIFF BIGS BIKE BILE BILK BILL BIMA BIND BINE BING BINS BINT BIOG BIOS BIRD BIRK BIRL BIRO BIRR BISE BISH BISK BITE BITS BITT BIZE BLAB BLAE BLAG BLAH BLAM BLAT BLAW BLEB BLED BLET BLEW BLIN BLIP BLOB BLOC BLOG BLOT BLOW BLUB BLUE BLUR BOAR BOAS BOAT BOBO BOBS BOCK BODE BODS BODY BOFF BOGS BOGY BOHO BOIL BOLA BOLD BOLE BOLL BOLO BOLT BOMB BOND BONE BONG BONK BONY BOOB BOOK BOOM BOON BOOR BOOS BOOT BOPS BORA BORE BORK BORN BORT BOSH BOSK BOSS BOTA BOTH BOTS BOTT BOUT BOWL BOWS BOXY BOYO BOYS BOZO BRAD BRAE BRAG BRAN BRAS BRAT BRAW BRAY BRED BREE BREN BREW BRIE BRIG BRIM BRIN BRIO BRIS BRIT BROO BROS BROW BRRR BRUT BRUX BUBO BUBS BUBU BUCK BUDS BUFF BUGS BUHL BUHR BULB BULK BULL BUMF BUMP BUMS BUNA BUND BUNG BUNK BUNN BUNS BUNT BUOY BURA BURB BURD BURG BURK BURL BURN BURP BURR BURS BURY BUSH BUSK BUSS BUST BUSY BUTE BUTS BUTT BUYS BUZZ BYES BYRE BYRL BYTE CABS CACA CADE CADI CADS CAFE CAFF CAFS CAGE CAGY CAID CAIN CAKE CAKY CALF CALK CALL CALM CALO CALS CALX CAME CAMI CAMO CAMP CAMS CANE CANS CANT CAPE CAPH CAPO CAPS CARB CARD CARE CARK CARL CARN CARP CARR CARS CART CASA CASE CASH CASK CAST CATE CATS CAUL CAVA CAVE CAVY CAWS CAYS CAZH CECA CEDE CEDI CEES CEIL CELL CELS CELT CENT CEPE CEPS CERE CERO CERT CESS CETE CHAD CHAI CHAM CHAO CHAP CHAR CHAT CHAW CHAY CHEF CHEM CHEW CHEZ CHIA CHIC CHID CHIN CHIP CHIS CHIT CHOC CHON CHOP CHOW CHUB CHUG CHUM CIAO CIGS CINE CINQ CION CIRE CIST CITE CITY CLAD CLAG CLAM CLAN CLAP CLAW CLAY CLEF CLEG CLEW CLIP CLIT CLOD CLOG CLON CLOP CLOT CLOY CLUB CLUE COAL COAT COAX COBB COBS COCA COCK COCO CODA CODE CODS COED COFF COFT COGS COHO COIF COIL COIN COIR COKE COKY COLA COLD COLE COLS COLT COLY COMA COMB COME COMM COMP CONE CONI CONK CONN CONS CONY COOF COOK COOL COON COOP COOS COOT COPE COPS COPY CORD CORE CORF CORK CORM CORN CORS CORY COSH COSS COST COSY COTE COTS COUP COVE COWL COWS COWY COXA COYS COZY CRAB CRAG CRAM CRAP CRAW CRED CREW CRIB CRIP CRIS CRIT CROC CROP CROW CRUD CRUS CRUX CUBE CUBS CUDS CUED CUES CUFF CUIF CUKE CULL CULM CULT CUMS CUNT CUPS CURB CURD CURE CURF CURL CURN CURR CURS CURT CUSK CUSP CUSS CUTE CUTS CWMS CYAN CYMA CYME CYST CZAR DABS DACE DADA DADO DADS DAFF DAFT DAGO DAGS DAHL DAHS DAIS DAKS DALE DALS DAME DAMN DAMP DAMS DANG DANK DANS DAPS DARB DARE DARK DARN DART DASH DATA DATE DATO DAUB DAUT DAVY DAWK DAWN DAWS DAWT DAYS DAZE DEAD DEAF DEAL DEAN DEAR DEBS DEBT DECK DECO DEED DEEM DEEP DEER DEES DEET DEFI DEFT DEFY DEIL DEKE DELE DELF DELI DELL DELS DELT DEME DEMO DEMY DENE DENI DENS DENT DENY DEPS DERE DERM DESI DESK DEVA DEVI DEVS DEWS DEWY DEXY DEYS DHAK DHAL DHOW DIAL DIBS DICE DICK DIDO DIDY DIED DIEL DIES DIET DIFF DIFS DIGS DIKE DILL DIME DIMS DINE DING DINK DINO DINS DINT DIOL DIPS DIPT DIRE DIRK DIRL DIRT DISC DISH DISK DISS DITA DITE DITS DITZ DIVA DIVE DJIN DOAT DOBE DOBY DOCK DOCS DODO DOER DOES DOFF DOGE DOGS DOGY DOHS DOIT DOJO DOLE DOLL DOLS DOLT DOME DOMS DONA DONE DONG DONS DOOB DOOM DOOR DOPA DOPE DOPY DORE DORK DORM DORP DORR DORS DORY DOSA DOSE DOSH DOSS DOST DOTE DOTH DOTS DOTY DOUM DOUR DOUT DOUX DOVE DOWN DOWS DOXY DOZE DOZY DRAB DRAG DRAM DRAT DRAW DRAY DREE DREG DREK DREW DRIB DRIP DROP DRUB DRUG DRUM DRYS DUAD DUAL DUBS DUCE DUCI DUCK DUCT DUDE DUDS DUEL DUES DUET DUFF DUGS DUIT DUKE DULL DULY DUMA DUMB DUMP DUNE DUNG DUNK DUNS DUNT DUOS DUPE DUPS DURA DURE DURN DURO DURR DUSK DUST DUTY DYAD DYED DYER DYES DYKE DYNE EACH EARL EARN EARS EASE EAST EASY EATH EATS EAUX EAVE EBBS EBON ECHE ECHO ECHT ECOS ECRU ECUS EDDO EDDY EDGE EDGY EDHS EDIT EEEW EELS EELY EERY EFFS EFTS EGAD EGAL EGER EGGS EGGY EGIS EGOS EIDE EKED EKES EKKA ELAN ELDS ELHI ELKS ELLS ELMS ELMY ELSE EMES EMEU EMIC EMIR EMIT EMMY EMOS EMUS EMYD ENDS ENGS ENOL ENOW ENUF ENVY EONS EPEE EPHA EPIC EPOS ERAS ERGO ERGS ERNE ERNS EROS ERRS ERST ERUV ESES ESNE ESPY ESSE ESTS ETAS ETCH ETHS ETIC ETNA ETUI EURO EVEN EVER EVES EVIL EWER EWES EXAM EXEC EXED EXES EXIT EXON EXPO EYAS EYED EYEN EYER EYES EYNE EYRA EYRE EYRY FABS FACE FACT FADE FADO FADS FAFF FAGS FAHS FAIL FAIN FAIR FAKE FALL FALX FAME FANE FANG FANO FANS FARD FARE FARL FARM FARO FART FASH FAST FATE FATS FAUN FAUX FAVA FAVE FAWN FAYS FAZE FEAL FEAR FEAT FECK FEDS FEEB FEED FEEL FEES FEET FEHS FELL FELT FEME FEMS FEND FENS FEOD FERE FERN FESS FEST FETA FETE FETS FEUD FEUS FIAR FIAT FIBS FICE FICO FIDO FIDS FIEF FIFE FIGS FILA FILE FILK FILL FILM FILO FILS FIND FINE FINK FINO FINS FIRE FIRM FIRN FIRS FISC FISH FIST FITS FIVE FIXT FIZZ FLAB FLAG FLAK FLAM FLAN FLAP FLAT FLAW FLAX FLAY FLEA FLED FLEE FLEW FLEX FLEY FLIC FLIP FLIR FLIT FLOC FLOE FLOG FLOP FLOW FLUB FLUE FLUS FLUX FOAL FOAM FOBS FOCI FOES FOGS FOGY FOHN FOIL FOIN FOLD FOLK FOND FONS FONT FOOD FOOL FOOS FOOT FOPS FORA FORB FORD FORE FORK FORM FORT FOSS FOUL FOUR FOWL FOXY FOYS FOZY FRAE FRAG FRAP FRAT FRAY FREE FRET FRIG FRIT FRIZ FROE FROG FROM FROW FRUG FUBS FUCI FUCK FUDS FUEL FUGS FUGU FUJI FULL FUME FUMY FUND FUNK FUNS FURL FURS FURY FUSE FUSS FUTZ FUZE FUZZ FYCE FYKE GABS GABY GACH GADI GADS GAED GAEN GAES GAFF GAGA GAGE GAGS GAIN GAIT GALA GALE GALL GALS GAMA GAMB GAME GAMP GAMS GAMY GANE GANG GAOL GAPE GAPS GAPY GARB GARS GASH GASP GAST GATE GATS GAUD GAUM GAUN GAUR GAVE GAWK GAWP GAYS GAZE GEAN GEAR GECK GEDS GEED GEEK GEES GEEZ GELD GELS GELT GEMS GENE GENS GENT GENU GERM GEST GETA GETS GEUM GHAT GHEE GHIS GIBE GIBS GIDS GIED GIEN GIES GIFS GIFT GIGA GIGS GILD GILL GILT GIMP GINK GINS GIPS GIRD GIRL GIRN GIRO GIRT GIST GITE GITS GIVE GLAD GLAM GLED GLEE GLEG GLEN GLEY GLIA GLIB GLIM GLOB GLOM GLOP GLOW GLUE GLUG GLUM GLUT GNAR GNAT GNAW GNUS GOAD GOAL GOAS GOAT GOBO GOBS GOBY GODS GOER GOES GOGO GOJI GOLD GOLF GONE GONG GOOD GOOF GOOK GOON GOOP GOOS GORE GORM GORP GORY GOSH GOTH GOUT GOWD GOWK GOWN GOYS GRAB GRAD GRAM GRAN GRAT GRAY GREE GREW GREY GRID GRIG GRIM GRIN GRIP GRIT GRIZ GROG GROK GROT GROW GRUB GRUE GRUM GUAN GUAR GUCK GUDE GUFF GUID GULF GULL GULP GULS GUMS GUNK GUNS GURU GUSH GUST GUTS GUVS GUYS GYBE GYMS GYNO GYPO GYPS GYRE GYRI GYRO GYVE HAAF HAAR HABU HACK HADE HADJ HAED HAEM HAEN HAES HAET HAFT HAGS HAHA HAHS HAIK HAIL HAIR HAJI HAJJ HAKE HAKU HALE HALF HALL HALM HALO HALT HAME HAMS HAND HANG HANK HANT HAPS HARD HARE HARK HARL HARM HARP HART HASH HASP HAST HATE HATH HATS HAUL HAUT HAVE HAWK HAWS HAYS HAZE HAZY HEAD HEAL HEAP HEAR HEAT HEBE HECK HEED HEEL HEFT HEHS HEIL HEIR HELD HELL HELM HELO HELP HEME HEMP HEMS HENS HENT HEPS HERB HERD HERE HERL HERM HERN HERO HERS HEST HETH HETS HEWN HEWS HICK HIDE HIED HIES HIGH HIKE HILA HILI HILL HILT HIMS HIND HINS HINT HIPS HIRE HISN HISS HIST HITS HIVE HIYA HMMM HOAR HOAX HOBO HOBS HOCK HODS HOED HOER HOES HOGG HOGS HOKE HOLD HOLE HOLK HOLM HOLO HOLP HOLS HOLT HOLY HOMA HOME HOMO HOMS HOMY HONE HONG HONK HONS HOOD HOOF HOOK HOOP HOOT HOPE HOPS HORA HORK HORN HOSE HOST HOTS HOUR HOVE HOWE HOWF HOWK HOWL HOWS HOYA HOYS HUBS HUCK HUED HUES HUFF HUGE HUGS HUIC HULA HULK HULL HUMP HUMS HUNG HUNH HUNK HUNS HUNT HURL HURT HUSH HUSK HUTS HWAN HWYL HYLA HYMN HYPE HYPO HYPS HYTE IAMB IBEX IBIS ICED ICES ICHS ICKS ICKY ICON IDEA IDEM IDES IDLE IDLY IDOL IDYL IFFY IGGS IGLU IKAT IKON ILEA ILEX ILIA ILKA ILKS ILLS ILLY IMAM IMID IMMY IMPI IMPS INBY INCH INFO INIA INKS INKY INLY INNS INRO INTI INTO IONS IOTA IRED IRES IRID IRIS IRKS IRON ISBA ISLE ISMS ITCH ITEM IWIS IXIA IZAR JABS JACK JADE JAGG JAGS JAIL JAKE JAMB JAMS JANE JAPE JARL JARS JATO JAUK JAUP JAVA JAWS JAYS JAZZ JEAN JEED JEEP JEER JEES JEEZ JEFE JEHU JELL JEON JERK JESS JEST JETE JETS JEUX JEWS JIAO JIBB JIBE JIBS JIFF JIGS JILL JILT JIMP JINK JINN JINS JINX JIRD JISM JIVE JIVY JIZZ JOBS JOCK JOES JOEY JOGS JOHN JOIN JOKE JOKY JOLE JOLT JOOK JOSH JOSS JOTA JOTS JOUK JOWL JOWS JOYS JUBA JUBE JUCO JUDO JUDY JUGA JUGS JUJU JUKE JUKU JUMP JUNK JUPE JURA JURY JUST JUTE JUTS KAAS KABS KADI KAES KAFS KAGU KAIF KAIL KAIN KAKA KAKI KALE KAME KAMI KANA KANE KAON KAPA KAPH KAPU KARN KART KATA KATS KAVA KAYO KAYS KBAR KEAS KECK KEEF KEEK KEEL KEEN KEEP KEET KEFS KEGS KEIR KELP KELT KEMP KENO KENS KENT KEPI KEPS KEPT KERB KERF KERN KETA KETO KEYS KHAF KHAN KHAT KHET KHIS KIBE KICK KIDS KIEF KIER KIFS KIKE KILL KILN KILO KILT KINA KIND KINE KING KINK KINO KINS KIPS KIRK KIRN KIRS KISS KIST KITE KITH KITS KIVA KIWI KLIK KNAP KNAR KNEE KNEW KNIT KNOB KNOP KNOT KNOW KNUR KOAN KOAS KOBO KOBS KOEL KOHL KOIS KOJI KOLA KOLO KONK KOOK KOPH KOPS KORA KORE KORS KOSS KOTO KRAI KRAY KRIS KUDO KUDU KUES KUFI KUNA KUNE KURU KVAS KYAK KYAR KYAT KYES KYTE LABS LACE LACK LACS LACY LADE LADS LADY LAGS LAHS LAIC LAID LAIN LAIR LAKE LAKH LAKY LALL LAMA LAMB LAME LAMP LAMS LAND LANE LANG LANK LAPS LARD LARI LARK LARN LARS LASE LASH LASS LAST LATE LATH LATI LATS LATU LAUD LAVA LAVE LAVS LAWN LAWS LAYS LAZE LAZY LEAD LEAF LEAK LEAL LEAN LEAP LEAR LEAS LECH LEDE LEEK LEER LEES LEET LEFT LEGS LEHR LEIS LEKE LEKS LEKU LEND LENO LENS LENT LEPT LESS LEST LETS LEUD LEVA LEVO LEVS LEVY LEWD LEYS LIAR LIAS LIBS LICE LICH LICK LIDO LIDS LIED LIEF LIEN LIER LIES LIEU LIFE LIFT LIKE LILO LILT LILY LIMA LIMB LIME LIMN LIMO LIMP LIMY LINE LING LINK LINN LINO LINS LINT LINY LION LIPA LIPE LIPO LIPS LIRA LIRE LIRI LISP LIST LITE LITS LITU LIVE LOAD LOAF LOAM LOAN LOBE LOBO LOBS LOCA LOCH LOCI LOCK LOCO LODE LOFT LOGE LOGO LOGS LOGY LOID LOIN LOLL LONE LONG LOOF LOOK LOOM LOON LOOP LOOS LOOT LOPE LOPS LORD LORE LORN LORY LOSE LOSS LOST LOTA LOTH LOTI LOTO LOTS LOUD LOUP LOUR LOUT LOVE LOWE LOWN LOWS LUAU LUBE LUCE LUCK LUDE LUDO LUDS LUES LUFF LUGE LUGS LULL LULU LUMA LUMP LUMS LUNA LUNE LUNG LUNK LUNS LUNT LUNY LURE LURK LUSH LUST LUTE LUTZ LUVS LUXE LWEI LYCH LYES LYNX LYRE LYSE MAAR MABE MACE MACH MACK MACS MADE MADS MAES MAGE MAGI MAGS MAID MAIL MAIM MAIN MAIR MAKE MAKI MAKO MALE MALL MALM MALT MAMA MAMS MANA MANE MANO MANS MANY MAPS MARA MARC MARE MARK MARL MARS MART MASA MASH MASK MASS MAST MATE MATH MATS MATT MAUD MAUL MAUN MAUT MAWN MAWS MAXI MAYA MAYO MAYS MAZE MAZY MEAD MEAL MEAN MEAT MECH MEDS MEED MEEK MEET MEGA MEGS MELD MELL MELS MELT MEME MEMO MEMS MEND MENO MENU MEOU MEOW MERC MERE MERK MERL MESA MESH MESS META METE METH MEWL MEWS MEZE MHOS MIBS MICA MICE MICK MICS MIDI MIDS MIEN MIFF MIGG MIGS MIKE MILD MILE MILK MILL MILO MILS MILT MIME MINA MIND MINE MINI MINK MINT MINX MIPS MIRE MIRI MIRK MIRS MIRY MISE MISO MISS MIST MITE MITT MITY MIXT MOAN MOAS MOAT MOBS MOCK MOCS MODE MODI MODS MOFO MOGS MOHO MOIL MOJO MOKE MOLA MOLD MOLE MOLL MOLS MOLT MOLY MOME MOMI MOMS MONK MONO MONS MONY MOOD MOOK MOOL MOON MOOR MOOS MOOT MOPE MOPS MOPY MORA MORE MORN MORS MORT MOSH MOSK MOSS MOST MOTE MOTH MOTS MOTT MOUE MOVE MOWN MOWS MOXA MOZO MUCH MUCK MUDS MUFF MUGG MUGS MULE MULL MUMM MUMP MUMS MUMU MUNG MUNI MUNS MUON MURA MURE MURK MURR MUSE MUSH MUSK MUSO MUSS MUST MUTE MUTS MUTT MYCS MYNA MYTH NAAN NABE NABS NADA NAES NAFF NAGA NAGS NAIF NAIL NALA NAME NANA NANO NANS NAOI NAOS NAPA NAPE NAPS NARC NARD NARK NARY NAVE NAVS NAVY NAYS NAZI NEAP NEAR NEAT NEBS NECK NEED NEEM NEEP NEGS NEIF NEMA NENE NEON NERD NESS NEST NETS NETT NEUK NEUM NEVE NEVI NEWB NEWS NEWT NEXT NIBS NICE NICK NIDE NIDI NIFF NIGH NILL NILS NIMS NINE NIPA NIPS NISI NITE NITS NIXE NIXY NOBS NOCK NODE NODI NODS NOEL NOES NOGG NOGS NOIL NOIR NOLO NOMA NOME NOMS NONA NONE NONI NOOK NOON NOPE NORI NORM NOSE NOSH NOSY NOTA NOTE NOUN NOUS NOVA NOWS NOWT NUBS NUDE NUFF NUGS NUKE NULL NUMB NUNS NURD NURL NUTS NYAH OAFS OAKS OAKY OARS OAST OATH OATS OATY OBAS OBES OBEY OBIA OBIS OBIT OBOE OBOL OCAS OCHE ODAH ODAS ODDS ODEA ODES ODIC ODOR ODYL OFAY OFFA OFFS OGAM OGEE OGLE OGRE OHED OHIA OHMS OIKS OILS OILY OINK OKAS OKAY OKEH OKES OKRA OLDE OLDS OLDY OLEA OLEO OLES OLIO OLLA OMAS OMEN OMER OMIT ONCE ONES ONLY ONOS ONTO ONUS ONYX OOHS OOPS OOTS OOZE OOZY OPAH OPAL OPAS OPED OPEN OPES OPTS OPUS ORAD ORAL ORBS ORBY ORCA ORCS ORDO ORES ORGS ORGY ORLE ORRA ORTS ORYX ORZO OSAR OSES OSSA OTIC OTTO OUCH OUDS OUPH OURS OUST OUTA OUTS OUZO OVAL OVEN OVER OVUM OWED OWES OWIE OWLS OWLY OWNS OWSE OWTS OXEN OXER OXES OXIC OXID OXIM OYER OYES OYEZ PAAN PACA PACE PACK PACS PACT PACY PADI PADS PAGE PAID PAIK PAIL PAIN PAIR PAKS PALE PALI PALL PALM PALP PALS PALY PAMS PANE PANG PANS PANT PAPA PAPS PARA PARD PARE PARK PARR PARS PART PASE PASH PASS PAST PATE PATH PATS PATY PAUA PAVE PAWL PAWN PAWS PAYS PEAG PEAK PEAL PEAN PEAR PEAS PEAT PECH PECK PECS PEDS PEED PEEK PEEL PEEN PEEP PEER PEES PEGS PEHS PEIN PEKE PELE PELF PELT PEND PENS PENT PEON PEPO PEPS PERC PERE PERI PERK PERM PERP PERT PERV PESO PEST PETS PEWS PFFT PFUI PHAT PHEW PHIS PHIZ PHON PHOS PHOT PHUT PIAL PIAN PIAS PICA PICE PICK PICS PIED PIER PIES PIGS PIKA PIKE PIKI PILE PILI PILL PILY PIMA PIMP PINA PINE PING PINK PINS PINT PINY PION PIPA PIPE PIPS PIPY PIRN PISH PISO PISS PITA PITH PITS PITY PIXY PLAN PLAT PLAY PLEA PLEB PLED PLEW PLEX PLIE PLOD PLOP PLOT PLOW PLOY PLUG PLUM PLUS POCK POCO PODS POEM POET POGO POGY POIS POKE POKY POLE POLL POLO POLS POLY POME POMO POMP POMS POND PONE PONG PONS PONY POOD POOF POOH POOL POON POOP POOR POOS POPE POPS PORE PORK PORN PORT POSE POSH POST POSY POTS POUF POUR POUT POWS POXY PRAM PRAO PRAT PRAU PRAY PREE PREP PREX PREY PREZ PRIG PRIM PROA PROB PROD PROF PROG PROM PROP PROS PROW PSIS PSST PTUI PUBS PUCE PUCK PUDS PUDU PUFF PUGH PUGS PUJA PUKE PULA PULE PULI PULK PULL PULP PULS PUMA PUMP PUNA PUNG PUNK PUNS PUNT PUNY PUPA PUPS PUPU PURE PURI PURL PURR PURS PUSH PUSS PUTS PUTT PUTZ PYAS PYES PYIC PYIN PYRE PYRO QADI QAID QATS QOPH QUAD QUAG QUAI QUAY QUEY QUID QUIN QUIP QUIT QUIZ QUOD RACE RACK RACY RADS RAFF RAFT RAGA RAGE RAGG RAGI RAGS RAIA RAID RAIL RAIN RAIS RAJA RAKE RAKI RAKU RALE RAMI RAMP RAMS RAND RANG RANI RANK RANT RAPE RAPS RAPT RARE RASE RASH RASP RATE RATH RATO RATS RAVE RAWS RAYA RAYS RAZE RAZZ READ REAL REAM REAP REAR REBS RECK RECS REDD REDE REDO REDS REED REEF REEK REEL REES REFS REFT REGS REIF REIN REIS RELY REMS REND RENO RENT REPO REPP REPS RESH REST RETE RETS REVS RHEA RHOS RHUS RIAL RIAS RIBS RICE RICH RICK RIDE RIDS RIEL RIFE RIFF RIFS RIFT RIGS RILE RILL RIME RIMS RIMY RIND RING RINK RINS RIOT RIPE RIPS RISE RISK RITE RITZ RIVE ROAD ROAM ROAN ROAR ROBE ROBS ROCK ROCS RODE RODS ROES ROIL ROLE ROLF ROLL ROMP ROMS ROOD ROOF ROOK ROOM ROOS ROOT ROPE ROPY ROSE ROSY ROTA ROTE ROTI ROTL ROTO ROTS ROUE ROUP ROUT ROUX ROVE ROWS RUBE RUBS RUBY RUCK RUDD RUDE RUED RUER RUES RUFF RUGA RUGS RUIN RUKH RULE RULY RUMP RUMS RUNE RUNG RUNS RUNT RUSE RUSH RUSK RUST RUTH RUTS RYAS RYES RYKE RYND RYOT RYUS SABE SABS SACK SACS SADE SADI SAFE SAGA SAGE SAGO SAGS SAGY SAID SAIL SAIN SAKE SAKI SALE SALL SALP SALS SALT SAME SAMP SAND SANE SANG SANK SANS SAPS SARD SARI SARK SASH SASS SATE SATI SAUL SAVE SAWN SAWS SAYS SCAB SCAD SCAG SCAM SCAN SCAR SCAT SCOP SCOT SCOW SCRY SCUD SCUM SCUP SCUT SEAL SEAM SEAR SEAS SEAT SECS SECT SEED SEEK SEEL SEEM SEEN SEEP SEER SEES SEGO SEGS SEIF SEIS SELF SELL SELS SEME SEMI SEND SENE SENT SEPS SEPT SERA SERE SERF SERS SESH SETA SETS SETT SEVS SEWN SEWS SEXT SEXY SHAD SHAG SHAH SHAM SHAT SHAW SHAY SHEA SHED SHEN SHES SHEW SHHH SHIM SHIN SHIP SHIT SHIV SHMO SHOD SHOE SHOG SHOO SHOP SHOT SHOW SHRI SHUL SHUN SHUT SHWA SIAL SIBB SIBS SICE SICK SICS SIDE SIDH SIFT SIGH SIGN SIGS SIKA SIKE SILD SILK SILL SILO SILT SIMA SIMP SIMS SINE SING SINH SINK SINS SIPE SIPS SIRE SIRS SITE SITH SITS SIZE SIZY SKAG SKAS SKAT SKED SKEE SKEG SKEP SKEW SKID SKIM SKIN SKIP SKIS SKIT SKOL SKRY SKUA SLAB SLAG SLAM SLAP SLAT SLAW SLAY SLED SLEW SLID SLIM SLIP SLIT SLOB SLOE SLOG SLOP SLOT SLOW SLUB SLUE SLUG SLUM SLUR SLUT SMEW SMIT SMOG SMUG SMUT SNAG SNAP SNAW SNED SNIB SNIP SNIT SNOB SNOG SNOT SNOW SNUB SNUG SNYE SOAK SOAP SOAR SOBA SOBS SOCA SOCK SODA SODS SOFA SOFT SOHS SOIL SOJA SOJU SOKE SOLA SOLD SOLE SOLI SOLO SOLS SOMA SOME SOMS SONE SONG SONS SOOK SOON SOOT SOPH SOPS SORA SORB SORD SORE SORI SORN SORT SOTH SOTS SOUK SOUL SOUP SOUR SOUS SOWN SOWS SOYA SOYS SPAE SPAM SPAN SPAR SPAS SPAT SPAY SPAZ SPEC SPED SPEW SPIC SPIK SPIN SPIT SPIV SPOT SPRY SPUD SPUE SPUN SPUR SRIS STAB STAG STAR STAT STAW STAY STEM STEP STET STEW STEY STIR STOA STOB STOP STOT STOW STUB STUD STUM STUN STYE SUBA SUBS SUCH SUCK SUDD SUDS SUED SUER SUES SUET SUGH SUIT SUKH SUKS SULK SULU SUMI SUMO SUMP SUMS SUMY SUNG SUNK SUNN SUNS SUPE SUPS SUQS SURA SURD SURE SURF SUSS SWAB SWAG SWAM SWAN SWAP SWAT SWAY SWIG SWIM SWOB SWOP SWOT SWUM SYBO SYCE SYKE SYLI SYNC SYNE SYPH TABS TABU TACE TACH TACK TACO TACT TADS TAEL TAGS TAHR TAIL TAIN TAKA TAKE TALA TALC TALE TALI TALK TALL TAME TAMP TAMS TANG TANK TANS TAOS TAPA TAPE TAPS TARE TARN TARO TARP TARS TART TASE TASK TASS TATE TATS TAUS TAUT TAVS TAWS TAXA TAXI TEAK TEAL TEAM TEAR TEAS TEAT TECH TECS TEDS TEED TEEL TEEM TEEN TEES TEFF TEGG TEGS TEGU TEIN TELA TELE TELL TELS TEMP TEND TENS TENT TEPA TERM TERN TEST TETH TETS TEWS TEXT THAE THAN THAT THAW THEE THEM THEN THEW THEY THIN THIO THIR THIS THOU THRO THRU THUD THUG THUS TIAN TICK TICS TIDE TIDY TIED TIER TIES TIFF TIKE TIKI TILE TILL TILS TILT TIME TINE TING TINS TINT TINY TIPI TIPS TIRE TIRL TIRO TITI TITS TIVY TIYN TIZZ TOAD TOBY TOCK TOCO TODS TODY TOEA TOED TOES TOFF TOFT TOFU TOGA TOGS TOIL TOIT TOKE TOLA TOLD TOLE TOLL TOLT TOLU TOMB TOME TOMS TONE TONG TONS TONY TOOK TOOL TOOM TOON TOOT TOPE TOPH TOPI TOPO TOPS TORA TORC TORE TORI TORN TORO TORR TORS TORT TORY TOSA TOSH TOSS TOST TOTE TOTS TOUR TOUT TOWN TOWS TOWY TOYO TOYS TRAD TRAM TRAP TRAY TREE TREF TREK TREM TRES TRET TREY TRIG TRIM TRIO TRIP TROD TROG TROP TROT TROU TROW TROY TRUE TRUG TSAR TSKS TUBA TUBE TUBS TUCK TUFA TUFF TUFT TUGS TUIS TULE TUMP TUMS TUNA TUNE TUNG TUNS TUPS TURD TURF TURK TURN TURR TUSH TUSK TUTS TUTU TWAE TWAS TWAT TWEE TWIG TWIN TWIT TWOS TYEE TYER TYES TYIN TYKE TYNE TYPE TYPO TYPP TYPY TYRE TYRO TZAR UDON UDOS UGHS UGLY UKES ULAN ULNA ULUS ULVA UMBO UMMA UMPH UMPS UNAI UNAU UNBE UNCI UNCO UNDE UNDO UNDY UNIS UNIT UNTO UPAS UPBY UPDO UPON URBS URDS UREA URGE URIC URNS URPS URSA URUS USED USER USES UTAS UTES UVEA VACS VAGI VAIL VAIN VAIR VALE VAMP VANE VANG VANS VAPE VARA VARS VARY VASA VASE VAST VATS VATU VAUS VAVS VAWS VEAL VEEP VEER VEES VEGA VEIL VEIN VELA VELD VENA VEND VENT VERA VERB VERT VERY VEST VETO VETS VEXT VIAL VIBE VICE VIDE VIDS VIED VIER VIES VIEW VIFF VIGA VIGS VILE VILL VIMS VINA VINE VINO VINS VINY VIOL VIRL VISA VISE VITA VIVA VIVE VLEI VLOG VOES VOGS VOID VOLE VOLK VOLT VOTE VOWS VROW VUGG VUGH VUGS VULN WAAH WABS WACK WADE WADI WADS WADY WAES WAFF WAFT WAGE WAGS WAIF WAIL WAIN WAIR WAIT WAKE WALE WALI WALK WALL WALY WAME WAND WANE WANK WANS WANT WANY WAPS WARD WARE WARK WARM WARN WARP WARS WART WARY WASH WASP WAST WATS WATT WAUK WAUL WAUR WAVE WAVY WAWL WAWS WAXY WAYS WEAK WEAL WEAN WEAR WEBS WEDS WEED WEEK WEEL WEEN WEEP WEER WEES WEET WEFT WEIR WEKA WELD WELL WELT WEND WENS WENT WEPT WERE WERT WEST WETA WETS WHAM WHAP WHAT WHEE WHEN WHET WHEW WHEY WHID WHIG WHIM WHIN WHIP WHIR WHIT WHIZ WHOA WHOM WHOP WHUP WHYS WICH WICK WIDE WIFE WIGS WIKI WILD WILE WILL WILT WILY WIMP WIND WINE WING WINK WINO WINS WINY WIPE WIRE WIRY WISE WISH WISP WISS WIST WITE WITH WITS WIVE WOAD WOES WOGS WOKE WOKS WOLD WOLF WOMB WONK WONS WONT WOOD WOOF WOOL WOOS WOPS WORD WORE WORK WORM WORN WORT WOST WOTS WOVE WOWS WRAP WREN WRIT WUSS WYCH WYES WYLE WYND WYNN WYNS WYTE XYST YACK YAFF YAGE YAGI YAGS YAKS YALD YAMS YANG YANK YAPS YARD YARE YARN YAUD YAUP YAWL YAWN YAWP YAWS YAYS YEAH YEAN YEAR YEAS YECH YEGG YELD YELK YELL YELP YENS YEOW YEPS YERK YETI YETT YEUK YEWS YIDS YILL YINS YIPE YIPS YIRD YIRR YLEM YOBS YOCK YODH YODS YOGA YOGH YOGI YOKE YOKS YOLK YOMP YOND YONI YOOF YORE YOUR YOUS YOWE YOWL YOWS YUAN YUCA YUCH YUCK YUGA YUKE YUKS YULE YUPS YURT YUTZ YUZU YWIS ZAGS ZANY ZAPS ZARF ZEAL ZEBU ZEDA ZEDS ZEES ZEIN ZEKS ZEPS ZERK ZERO ZEST ZETA ZIGS ZILL ZINC ZINE ZING ZINS ZIPS ZITI ZITS ZIZZ ZOEA ZOIC ZONA ZONE ZONK ZOOM ZOON ZOOS ZORI ZOUK ZYME
""".upper().split()

if "score" not in st.session_state:
    st.session_state.score = 0

if "p" not in st.session_state:
    st.session_state.p = "Guest"

if "page" not in st.session_state:
    st.session_state.page = "home"

if "profile_pic" not in st.session_state:
    try:
        _localS_boot = LocalStorage()
        _saved_pic = _localS_boot.getItem("profile_pic_b64")
        st.session_state.profile_pic = _saved_pic if _saved_pic else None
    except Exception:
        st.session_state.profile_pic = None

def render_profile_badge():
    if st.session_state.get("profile_pic"):
        pic_html = f'<img src="data:image/png;base64,{st.session_state.profile_pic}" style="width:28px;height:28px;border-radius:50%;object-fit:cover;">'
    else:
        pic_html = '<div style="width:28px;height:28px;border-radius:50%;background:#dfbf9f;display:flex;align-items:center;justify-content:center;font-size:14px;">🙂</div>'

    st.markdown(f"""
    <div style="display:flex; align-items:center; gap:8px; margin-bottom:0.5vw;">
        {pic_html}
        <span style="font-size:0.85vw; min-font-size:12px; color:#555;">{st.session_state.get('p', 'Guest')}</span>
    </div>
    """, unsafe_allow_html=True)

render_profile_badge()

if st.session_state.page == "home":
    st.markdown("""
    <style>
    .stApp {
    background-color: #ecd9c6;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }

    .stButton {
    }
    </style>

    <div class = "divvy">Scrabblapp - Home</div>
    """, unsafe_allow_html = True)

    if st.button(" Word Checker"):
        st.session_state.page = "check"
        st.rerun()
    if st.button("2 Letter S Quiz"):
        st.session_state.page = "quizsyy"
        st.rerun()
    if st.button(" 3 Letter Quiz"):
        st.session_state.page = "quiz1"
        st.rerun()
    if st.button(" Vowel Dump Quiz"):
        st.session_state.page = "quiz2"
        st.rerun()
    if st.button("BINGO Quiz - HARD"):
        st.session_state.page = "quiz3"
        st.rerun()
    if st.button("Easy Bingo Checker"):
        st.session_state.page = "bingof"
        st.rerun()
    if st.button("BINGO Quiz - EASY"):
        st.session_state.page = "quiz4"
        st.rerun()
    if st.button("Contact Creators"):
        st.session_state.page = "cc"
        st.rerun()
    if st.button("Credits"):
        st.session_state.page = "c"
        st.rerun()
    if st.button("Helpful Videos"):
        st.session_state.page = "v"
        st.rerun()
    
    if st.button("2s for Popo"):
        st.session_state.page = "random_2s"
        st.rerun()
    
    if st.button(" Stats"):
        st.session_state.page = "s"
        st.rerun()
    
    if st.button("Super 3s"):
        st.session_state.page = "super"
        st.rerun()

    if st.button("Custom"):
        st.session_state.page = "cu"
        st.rerun()
    if st.button("Bad Quiz"):
        st.session_state.page = "bad_quiz"
        st.rerun()
    if st.button("Fours Frenzy"):
        st.session_state.page = "foursfrenzy"
        st.rerun()
    if st.button("My Word List"):
        st.session_state.page = "mywordlist"
        st.rerun()
    if st.button("Threes Hooks Quiz"):
        st.session_state.page = "threehooks"
        st.rerun()
if st.session_state.page == "random_2s":
    # ✨ RANDOM 2s QUIZ

    import random
    import string

    # paste all valid 2-letter words here
    quiz_words = """
AA
AB
AD
AE
AG
AH
AI
AL
AM
AN
AR
AS
AT
AW
AX
AY
BA
BE
BI
BO
BY
DA
DE
DO
ED
EF
EH
EL
EM
EN
ER
ES
ET
EW
EX
FA
FE
GI
GO
HA
HE
HI
HM
HO
ID
IF
IN
IS
IT
JO
KA
KI
LA
LI
LO
MA
ME
MI
MM
MO
MU
MY
NA
NE
NO
NU
OD
OE
OF
OH
OI
OK
OM
ON
OP
OR
OS
OW
OX
OY
PA
PE
PI
PO
QI
RE
SH
SI
SO
TA
TE
TI
TO
UH
UM
UN
UP
US
UT
WE
WO
XI
XU
YA
YE
YO
ZA
    """.split()

    VOWELS = "AEIOU"
    CONSONANTS = "".join([c for c in string.ascii_uppercase if c not in VOWELS])

    # 😈 SMART FAKE 2-LETTER GENERATOR
    def generate_fake_word():
        patterns = ["CV", "VC"]  # only consonant-vowel or vowel-consonant

        while True:
            pattern = random.choice(patterns)
            word = ""

            for p in pattern:
                if p == "C":
                    word += random.choice(CONSONANTS)
                else:
                    word += random.choice(VOWELS)

            # avoid weird Q words
            if "Q" in word and "I" not in word:
                continue

            return word

    # 🎲 choose real or fake
    def get_word():
        if random.random() < 0.3:
            word = random.choice(quiz_words)
            is_real = True
        else:
            word = generate_fake_word()

            # ✅ if generated word accidentally IS real
            is_real = word in quiz_words

        return word, is_real

    # session state
    if "score_2s" not in st.session_state:
        st.session_state.score_2s = 0

    if "random_word_2s" not in st.session_state:
        st.session_state.random_word_2s, st.session_state.is_real_2s = get_word()

    if "answered_2s" not in st.session_state:
        st.session_state.answered_2s = False

    # UI
    st.markdown("""
    <style>
    .stApp { background-color: #ecd9c6; }

    .divvy {
        color: #dfbf9f;
        background-color: #ffffff;
        padding-top: 1vw;
        padding-bottom: 1vw;
        text-align: center;
        font-size: 3vw;
        border-radius: 1.5vw;
        margin-bottom: 1.5vw;
    }
    </style>

    <div class="divvy">Scrabble Practice - Random 2s</div>
    """, unsafe_allow_html=True)

    st.write("Is", st.session_state.random_word_2s, "a valid Scrabble word?")

    choice = st.radio("Choose one:", ["Yes", "No"])

    if st.button("Check Answer") and not st.session_state.answered_2s:
        st.session_state.answered_2s = True

        if (choice == "Yes" and st.session_state.is_real_2s) or \
           (choice == "No" and not st.session_state.is_real_2s):

            st.success("Yes, you got it right! 😎")
            st.session_state.score_2s += 1

        else:
            st.error("Sorry, you got it wrong 😬")

    if st.button("Next Question"):
        st.session_state.random_word_2s, st.session_state.is_real_2s = get_word()
        st.session_state.answered_2s = False
        st.rerun()

    st.write(f"Score: {st.session_state.score_2s}")

    st.image("https://upload.wikimedia.org/wikipedia/commons/6/6d/Scrabble_2.jpg")

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()
if st.session_state.page == "bad_quiz":
    # 😈 BAD QUIZ
    quiz_word = "BIR"
    is_real = False  # BIR is NOT valid in NWL

    # session state
    if "bad_score" not in st.session_state:
        st.session_state.bad_score = 0
    if "bad_answered" not in st.session_state:
        st.session_state.bad_answered = False

    # UI
    st.markdown("""
    <style>
    .stApp { background-color: #ecd9c6; }
    .divvy {
        color: #dfbf9f;
        background-color: #ffffff;
        padding-top: 1vw;
        padding-bottom: 1vw;
        text-align: center;
        font-size: 3vw;
        border-radius: 1.5vw;
        margin-bottom: 1.5vw;
    }
    </style>
    <div class="divvy">Bad Quiz</div>
    """, unsafe_allow_html=True)

    st.write("Is", quiz_word, "a valid Scrabble word?")

    choice = st.radio("Choose one:", ["Yes", "No"])

    if st.button("Check Answer") and not st.session_state.bad_answered:
        st.session_state.bad_answered = True

        if (choice == "Yes" and is_real) or \
        (choice == "No" and not is_real):
            st.success("Yes, you got it right! 😎")
            st.session_state.bad_score += 1
        else:
            st.error("Sorry, you got it wrong 😬")

    if st.button("Next Question"):
        st.session_state.bad_answered = False
        st.rerun()

    st.write(f"Score: {st.session_state.bad_score}")

    st.image("https://upload.wikimedia.org/wikipedia/commons/6/6d/Scrabble_2.jpg")

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()
        
if st.session_state.page == "quizsyy":
    st.markdown("""
    <style>
        .stApp {
            background-color: #ecd9c6;
        }

        .divvy {
            color: #dfbf9f;
            background-color: #ffffff;
            padding-top: 1vw;
            padding-bottom: 1vw;
            text-align: center;
            font-size: 3vw;
            border-radius: 1.5vw;
            margin-bottom: 1.5vw;
        }
    </style>

    <div class = "divvy">Scrabble Practice - 2 Letter S Hooks</div>
    """, unsafe_allow_html=True)

    if "random_two" not in st.session_state:
        st.session_state.random_two = random.choice(two_letter_words)

    if "answered_two" not in st.session_state:
        st.session_state.answered_two = False

    word = st.session_state.random_two

    st.write("Does", word, "take an S hook?")

    choice = st.radio(
        "Choose one:",
        ["Yes", "No"],
        key="squiz_" + word
    )

    if st.button("Check Answer!!!") and not st.session_state.answered_two:

        st.session_state.answered_two = True

        takes_s = word not in no_s_words

        if (choice == "Yes" and takes_s) or \
        (choice == "No" and not takes_s):

            st.success("Correct 😎")
            st.session_state.score += 1

        else:
            if takes_s:
                st.error("Wrong 😬 " + word + " DOES take an S.")
            else:
                st.error("Wrong 😬 " + word + " does NOT take an S.")

    if st.button("Next Question"):

        st.session_state.random_two = random.choice(two_letter_words)
        st.session_state.answered_two = False
        st.rerun()

    st.write("Words that do NOT take an S:")
    st.write(no_s_words)

    st.write("Score:", st.session_state.score)

    st.image("https://upload.wikimedia.org/wikipedia/commons/6/6d/Scrabble_2.jpg")

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()    
if st.session_state.page == "cu":
    # 🔥 SUPER 3s (quiz list)
    quiz_words = """
    TYE RIN MOL MEM UPO HOD MIR BYS UKE JOW DOL URD NOH POI ACK HUP FEH PHI TAW BOS HES RET ETH NEB KIS DEX KEX TAM FOO HOO ZEP KEA DEL LEA KOB POH WHA WAE FON LEU REI KUE NEB UPO TAM KOP KEX NOH TYE OUD RIN PHI WYE RHO MEL RAS TAW NAW POH URD WOT OLE UMM POI YOW RYU TED HAE TET TAE MOL WAE DOM MOG LEY UMM TOD AMA EFT HYP FON RHO SAL PAK ICH YOW VAU VAW GHI ENG NAW LUN MAE DAK REE ELL RAS OIK LIB DIS KIP UTE LAT GOX MYC WYE POM YAW GIB ORT SAB SEC
    """.split()

    VOWELS = "AEIOU"
    CONSONANTS = "".join([c for c in string.ascii_uppercase if c not in VOWELS])

    # 😈 SMART FAKE GENERATOR
    def generate_fake_word():
        patterns = ["CVC", "CVC", "CVC", "CVV", "VCC"]
        
        while True:
            pattern = random.choice(patterns)
            word = ""
            
            for p in pattern:
                if p == "C":
                    word += random.choice(CONSONANTS)
                else:
                    word += random.choice(VOWELS)
            
            if "Q" in word and "U" not in word:
                continue
            
            if any(x in word for x in ["ZX", "QZ", "JQ"]):
                continue
            
            return word

    def get_word():
        if random.random() < 0.5:
            word = random.choice(quiz_words)
            is_real = True
        else:
            word = generate_fake_word()
            is_real = word in three_letter_words  # ✅ check full dictionary
        
        return word, is_real

    # session state
    if "score" not in st.session_state:
        st.session_state.score = 0
    if "random_word" not in st.session_state:
        st.session_state.random_word, st.session_state.is_real = get_word()
    if "answered" not in st.session_state:
        st.session_state.answered = False

    # UI
    st.markdown("""
    <style>
    .stApp { background-color: #ecd9c6; }
    .divvy {
        color: #dfbf9f;
        background-color: #ffffff;
        padding-top: 1vw;
        padding-bottom: 1vw;
        text-align: center;
        font-size: 3vw;
        border-radius: 1.5vw;
        margin-bottom: 1.5vw;
    }
    </style>
    <div class="divvy">Scrabble Practice - Custom</div>
    """, unsafe_allow_html=True)

    st.write("Is", st.session_state.random_word, "a valid Scrabble word?")

    choice = st.radio("Choose one:", ["Yes", "No"])

    if st.button("Check Answer") and not st.session_state.answered:
        st.session_state.answered = True
        
        if (choice == "Yes" and st.session_state.is_real) or \
        (choice == "No" and not st.session_state.is_real):
            st.success("Yes, you got it right! 😎")
            st.session_state.score += 1
        else:
            st.error("Sorry, you got it wrong 😬")

    if st.button("Next Question"):
        st.session_state.random_word, st.session_state.is_real = get_word()
        st.session_state.answered = False
        st.rerun()

    st.write(f"Score: {st.session_state.score}")

    st.image("https://upload.wikimedia.org/wikipedia/commons/6/6d/Scrabble_2.jpg")

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()
    
if st.session_state.page == "quizs":
    st.markdown("""
    <style>
        .stApp {
            background-color: #ecd9c6;
        }

        .divvy {
            color: #dfbf9f;
            background-color: #ffffff;
            padding-top: 1vw;
            padding-bottom: 1vw;
            text-align: center;
            font-size: 3vw;
            border-radius: 1.5vw;
            margin-bottom: 1.5vw;
        }
    </style>

    <div class = "divvy">Scrabble Practice - 2 Letter S Hooks</div>
    """, unsafe_allow_html=True)

    if "random_two" not in st.session_state:
        st.session_state.random_two = random.choice(two_letter_words)

    if "answered_two" not in st.session_state:
        st.session_state.answered_two = False

    word = st.session_state.random_two

    st.write("Does", word, "take an S hook?")

    choice = st.radio(
        "Choose one:",
        ["Yes", "No"],
        key="squiz"
    )

    if st.button("Check Answer") and not st.session_state.answered_two:

        st.session_state.answered_two = True

        takes_s = word not in no_s_words

        if (choice == "Yes" and takes_s) or \
        (choice == "No" and not takes_s):

            st.success("Correct 😎")
            st.session_state.score += 1

        else:
            if takes_s:
                st.error("Wrong 😬 " + word + " DOES take an S.")
            else:
                st.error("Wrong 😬 " + word + " does NOT take an S.")

    if st.button("Next Question"):

        st.session_state.random_two = random.choice(two_letter_words)
        st.session_state.answered_two = False
        st.rerun()

    st.write("Words that do NOT take an S:")
    st.write(no_s_words)

    st.write("Score:", st.session_state.score)

    st.image("https://upload.wikimedia.org/wikipedia/commons/6/6d/Scrabble_2.jpg")

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()

if st.session_state.page == "super":
    VOWELS = "AEIOU"
    CONSONANTS = "".join([c for c in string.ascii_uppercase if c not in VOWELS])

    def generate_fake_word():
        num_vowels = random.randint(1, 2)
        num_consonants = 3 - num_vowels
        
        letters = []
        for _ in range(num_vowels):
            letters.append(random.choice(VOWELS))
        for _ in range(num_consonants):
            letters.append(random.choice(CONSONANTS))
        
        random.shuffle(letters)
        return "".join(letters)

    def get_word():
        if random.random() < 0.5:
            word = random.choice(three_letter_words)
            is_real = True
        else:
            word = generate_fake_word()
            is_real = word in three_letter_words
        return word, is_real

    # session state
    if "score" not in st.session_state:
        st.session_state.score = 0
    if "random_word" not in st.session_state:
        st.session_state.random_word, st.session_state.is_real = get_word()
    if "answered" not in st.session_state:
        st.session_state.answered = False

    # UI
    st.markdown("""
    <style>
    .stApp { background-color: #ecd9c6; }
    .divvy {
        color: #dfbf9f;
        background-color: #ffffff;
        padding-top: 1vw;
        padding-bottom: 1vw;
        text-align: center;
        font-size: 3vw;
        border-radius: 1.5vw;
        margin-bottom: 1.5vw;
    }
    </style>
    <div class="divvy">Scrabble Practice - Super 3s Challenge</div>
    """, unsafe_allow_html=True)

    st.write("Is", st.session_state.random_word, "a valid Scrabble word?")

    choice = st.radio("Choose one:", ["Yes", "No"])

    if st.button("Check Answer") and not st.session_state.answered:
        st.session_state.answered = True
        if (choice == "Yes" and st.session_state.is_real) or \
        (choice == "No" and not st.session_state.is_real):
            st.success("Yes, you got it right! 😎")
            st.session_state.score += 1
        else:
            st.error("Sorry, you got it wrong 😬")

    if st.button("Next Question"):
        st.session_state.random_word, st.session_state.is_real = get_word()
        st.session_state.answered = False
        st.rerun()

    st.write(f"Score: {st.session_state.score}")

    st.image("https://upload.wikimedia.org/wikipedia/commons/6/6d/Scrabble_2.jpg")

    if st.button("Back"):
        st.session_state.page = "home"

if st.session_state.page == "threehooks":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Threes Hooks Quiz</div>
    """, unsafe_allow_html = True)

    # use the full valid word lists (global), not the user's personal saved lists
    threes_pool = list(three_letter_words)
    fours_pool = list(four_letter_words)

    def get_hook_question():
        word = random.choice(threes_pool)
        alphabet = list(string.ascii_uppercase)
        random.shuffle(alphabet)

        # find every real (word, letter, position) hook for this base word
        real_candidates = []
        for letter in string.ascii_uppercase:
            front = letter + word
            back = word + letter
            if front in fours_pool:
                real_candidates.append(front)
            if back in fours_pool:
                real_candidates.append(back)

        use_real = bool(real_candidates) and random.random() < 0.8

        chosen_words = []
        used_letters = set()

        if use_real:
            correct = random.choice(real_candidates)
            chosen_words.append(correct)
            # figure out which letter that used, so we don't reuse it as a distractor
            if correct[1:] == word:
                used_letters.add(correct[0])
            else:
                used_letters.add(correct[-1])
        else:
            correct = "None of the above"

        # fill remaining slots with fake (non-valid) candidate words
        idx = 0
        while len(chosen_words) < 3 and idx < len(alphabet):
            letter = alphabet[idx]
            idx += 1
            if letter in used_letters:
                continue
            position = random.choice(["front", "back"])
            candidate = letter + word if position == "front" else word + letter
            if candidate in fours_pool or candidate in chosen_words:
                continue
            chosen_words.append(candidate)
            used_letters.add(letter)

        random.shuffle(chosen_words)
        options = chosen_words + ["None of the above"]
        return word, options, correct

    def evaluate_word_hook(word, candidate):
        if candidate[1:] == word:
            position = "front"
        elif candidate[:len(word)] == word:
            position = "back"
        else:
            position = None
        valid = candidate in fours_pool
        return valid, position

    if "hook_word" not in st.session_state:
        st.session_state.hook_word, st.session_state.hook_options, st.session_state.hook_correct = get_hook_question()

    if "hook_answered" not in st.session_state:
        st.session_state.hook_answered = False

    st.write(f"Hooks for **{st.session_state.hook_word}**:")

    option_labels = [f"{i+1}. {opt}" for i, opt in enumerate(st.session_state.hook_options)]
    picked_label = st.radio("Choose one:", option_labels, key="hook_radio_" + st.session_state.hook_word)
    picked_index = option_labels.index(picked_label)
    picked_option = st.session_state.hook_options[picked_index]

    if st.button("Check Answer") and not st.session_state.hook_answered:
        st.session_state.hook_answered = True

        word = st.session_state.hook_word

        if picked_option != "None of the above":
            valid, position = evaluate_word_hook(word, picked_option)

            if valid:
                st.success(f"✅ Valid! **{picked_option}** is a real word — a **{position} hook** on '{word}'.")
                st.session_state.score += 1
            else:
                st.error(f"❌ Not valid. **{picked_option}** isn't a real word.")
        else:
            if st.session_state.hook_correct == "None of the above":
                st.success(f"✅ Correct — none of the shown words are real.")
                st.session_state.score += 1
            else:
                correct_word = st.session_state.hook_correct
                _, position = evaluate_word_hook(word, correct_word)
                st.error(f"❌ Not quite. **{correct_word}** actually IS a real word — a **{position} hook** on '{word}'.")

    if st.button("Next Question"):
        st.session_state.hook_word, st.session_state.hook_options, st.session_state.hook_correct = get_hook_question()
        st.session_state.hook_answered = False
        st.rerun()

    st.write("Score:", st.session_state.score)

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()

if st.session_state.page == "s":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Stats</div>
    """, unsafe_allow_html = True)

    st.subheader("Profile Picture")

    if st.session_state.get("profile_pic"):
        st.image(base64.b64decode(st.session_state.profile_pic), width=120)
    else:
        st.write("No profile picture set yet.")

    new_pic = st.file_uploader("Change profile picture", type=["png", "jpg", "jpeg"])

    if new_pic is not None:
        pic_bytes = new_pic.read()
        b64_pic = base64.b64encode(pic_bytes).decode()
        st.session_state.profile_pic = b64_pic
        try:
            localS_profile = LocalStorage()
            localS_profile.setItem("profile_pic_b64", b64_pic)
        except Exception:
            pass
        st.success("Profile picture updated!")
        st.rerun()

    if st.session_state.get("profile_pic"):
        if st.button("Remove Profile Picture"):
            st.session_state.profile_pic = None
            try:
                localS_profile2 = LocalStorage()
                localS_profile2.setItem("profile_pic_b64", "")
            except Exception:
                pass
            st.rerun()

    st.write("Change name?")
    i = st.text_input("")

    st.write("Name : " , st.session_state.p)

    st.write("Delete the letters in the username box for the program to run - don't worry, your username will be saved! ")

    if i != "":
        st.session_state.p = i
        st.rerun()
    if st.session_state.score < 50:
        st.write("Your level : Beginner")
    if st.session_state.score >= 50:
        if st.session_state.score <= 100:
            st.write("Your level : Intermediate")
    if st.session_state.score > 100:
        if st.session_state.score <= 150:
            st.write("Your level : Advanced")
    if st.session_state.score > 150:
        st.write("Your level : Expert")    
    
    st.write("Your score : " , st.session_state.score)

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()

if st.session_state.page == "v":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Videos</div>
    """, unsafe_allow_html = True)

    st.write("Courtesy of Will Anderson and no laws were broken :). Go to his channel to see more videos!")

    st.video("https://www.youtube.com/watch?v=NxizYoHaIf0")
    st.video("https://www.youtube.com/watch?v=nZdiSggMUsg")
    st.video("https://www.youtube.com/watch?v=wVoz8OSjlvo")
    st.video("https://www.youtube.com/watch?v=-MEy8TdWlPE")
    st.video("https://www.youtube.com/watch?v=2boBX9lAtS4")
    st.video("https://www.youtube.com/watch?v=AJIAlRSs214")
    st.video("https://www.youtube.com/watch?v=6ytmzCI27Kk")
    st.video("https://www.youtube.com/watch?v=j3udQk1XWBI")
    st.video("https://www.youtube.com/watch?v=qQ9NBmeOci4")
    st.video("https://www.youtube.com/watch?v=whLN4aF2xfE")
    st.video("https://www.youtube.com/watch?v=uOhBed1ujGc")
    st.video("https://www.youtube.com/watch?v=2erXTsAAhg0")
    st.video("https://www.youtube.com/watch?v=9120Php3Kh4")
    st.video("https://www.youtube.com/watch?v=EzbOrbWxliY")
    st.video("https://www.youtube.com/watch?v=TSZn-c3gUFU")
    st.video("https://www.youtube.com/watch?v=PeXLFwYmqv0")
    st.video("https://www.youtube.com/watch?v=vxAHFz90K34")
    st.video("https://www.youtube.com/watch?v=lSLS7tq4C2Y")
    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()
if st.session_state.page == "c":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Credits</div>
    """, unsafe_allow_html = True)

    st.write("Me - for making")
    st.write("ChatGPT - for helping with word lists and generator")
    st.write("NASPA - for Cheat Sheet Lists :)")
    st.write("Will Anderson for Scrabble videos")

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()    



if st.session_state.page == "cc":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Contact Creators</div>
    """, unsafe_allow_html = True)
    st.write("Any ideas, bugs, or word lists? Send them here!")

    st.write("Contact creators at : ")
    st.write("[REDACTED]@gmail.com")

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()

if st.session_state.page == "check":
    st.markdown("""
   
    <style>
         .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Scrabble Word Checker - 3s</div>
    """, unsafe_allow_html = True)

    st.title("Valid 3 Letter Scrabble Word Checker for Naspa")
    st.write("Please note that this list is to be updated as it is missing 5 - 10 new words.")

    ans = st.text_input("Enter your 3 letter word (Type out in All Caps) :")

    if ans:
        if ans in three_letter_words:
            st.write("Allowed!")
        else:
            st.write("This is not a valid 3 letter word in Naspa.")

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()

if st.session_state.page == "quiz1":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Scrabble Practice - Odd 3s</div>
    """, unsafe_allow_html = True)

    words = np.array(["Edh", "Kax", "Mux", "Lux", "Aji", "Tac", "Orc", "Mia", "Erg", "Por", "Mim", "Kib", "Que", "Oes", "Aux", "Vug", "Ken", "Kef", "Khi", "Lac", "Lor", "Rax", "Fiz", "Tux", "Gox", "Ric", "Tex", "Exe", "Rox", "Kew", "Loh", "Kew", "Lah", "Kee", "Bir", "Mir", "Cox", "Raz", "Daz", "Cuz", "Zuz", "Lix", "Mex", "Lol", "Dru"])
    wordsRight = np.array(["Edh", "Mux", "Lux", "Aji", "Orc", "Erg", "Por", "Mim", "Vug", "Khi", "Ken", "Kef", "Lac", "Lor", "Kue", "Lah", "Mir", "Cox", "Cuz", "Zuz", "Rax", "Fiz", "Tux", "Gox"])
    result = ""

    if "random_word" not in st.session_state:
        st.session_state.random_word = np.random.choice(words)

    st.write(" Is", st.session_state.random_word, "a valid Scrabble word?")


    if st.session_state.random_word in wordsRight:
        if st.checkbox("Yes"):
            result = " Yes, you got it right!"
            st.session_state.score += 1
        if st.checkbox("No"):
            result = " Sorry, you got it wrong!"
    else:
        if st.checkbox("Yes"):
            result = " Sorry, you got it wrong!"
        if st.checkbox(" No"):
            result = " Yes, you got it right!"

            st.session_state.score += 1

    if st.button("Check Answer"):
        st.write(result)

    if st.button("Next Question"):
        st.session_state.random_word = np.random.choice(words)

        st.rerun()

    st.image("https://upload.wikimedia.org/wikipedia/commons/6/6d/Scrabble_2.jpg")
    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()

if st.session_state.page == "quiz2":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Scrabble Practice - Vowel Dumps</div>
    """, unsafe_allow_html = True)

    words2 = np.array(["aeon",  "awee", "akee", "ajee", "amee", "aurei", "aroai", "aecia", "ohiai", "oidia", "miaou", "paua", "omeia", "loui", "iona", "inia", "moue", "ouzo", "azoia", "zoeae", "aerie", "aeria", "naoi", "oaho", "eide"])
    wordsRight2 = np.array(["aeon", "awee", "akee", "ajee", "aurei", "aecia", "oidia", "miaou", "paua", "inia", "moue", "ouzo", "zoeae", "aerie", "naoi", "eide"])
    result2 = ""

    if "random_word2" not in st.session_state:
        st.session_state.random_word2 = np.random.choice(words2)

    st.write(" Is", st.session_state.random_word2, "a valid Scrabble word?")


    if st.session_state.random_word2 in wordsRight2:
        if st.checkbox(" Yes"):
            result2 = " Yes, you got it right!"

            st.session_state.score += 1
        if st.checkbox(" No"):
            result2 = " Sorry, you got it wrong!"
    else:
        if st.checkbox(" Yes"):
            result2 = " Sorry, you got it wrong!"
        if st.checkbox(" No"):
            result2 = " Yes, you got it right!"

            st.session_state.score += 1

    if st.button("Check Answer"):
        st.write(result2)

    if st.button("Next Question"):
        st.session_state.random_word2 = np.random.choice(words2)

        st.rerun()

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()



if st.session_state.page == "quiz3":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Scrabble Practice - HARD Bingos</div>
    """, unsafe_allow_html = True)

    #(AAH HE MADE SO MANY MISTAKES) Credit to ChatGPT for some bingo things, since it would be very tough to write out all the only one word inside bingo stems (or one obvious word)
    words3 = np.array(["AHURELS", "PIGCONO", "CROERAL", "AWCERLD", "MEGARAN",  "EONMSTR",  "ERACHTN",  "RELACIT", "RETISGN", "NAGARMA", "LACIGAM", "ERIMNOB", "UROFELD", "YORHMAN", "LIMOUTR", "DRNEDKI", "PLDNOIH", "KNPMUPI"])
    wordsRight3 = np.array(["HAULERS", "COOPING", "CAROLER", "CRAWLED", "MANAGER", "MONSTER", "CHANTER","ARTICLE", "RESTING", "ANAGRAM", "MAGICAL", "BROMINE", "FLOURED", "HARMONY", "TURMOIL", "KINDRED", "DOLPHIN", "PUMPKIN"])
    nums = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])
    result3 = ""

    if "random_numm" not in st.session_state:
        st.session_state.random_numm = np.random.choice(nums)

    st.write(" Name a bingo with", words3[st.session_state.random_numm], "! ( PLEASE ANSWER IN ALL CAPS )")

    hh = st.text_input("")
    
    if hh == wordsRight3[st.session_state.random_numm]:
        result3 = "Correct!"

        st.session_state.score += 1
    else:
        result3 = "Incorrect Bingo!"

    if st.button("See Answer"):
        st.write(wordsRight3[st.session_state.random_numm])

    if st.button("Check Answer"):
        st.write(result3)

    if st.button("Next Question"):
        st.session_state.random_numm = np.random.choice(nums)

        st.rerun()

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()

if st.session_state.page == "bingof":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Scrabble Practice - Easy Bingo Finder</div>
    """, unsafe_allow_html = True)
    st.write("Only for Hi Prob 7s and those in Top Bingo Stems. Please enter in ALL CAPS.")
    
    pp = st.text_input("Your Rack : ")
 
    for w in bingoes:
        if sorted(w) == sorted(pp):
            st.write(w)
    
    st.write("If nothing returns, there are no easy bingoes logged in our word finder.")

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()

if st.session_state.page == "quiz4":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Scrabble Practice - EASY Bingos</div>
    """, unsafe_allow_html = True)
    result4 = ""

    if "random_num" not in st.session_state:
        st.session_state.random_num = np.random.randint(0, len(bingoes))

    st.write(" Name a bingo with", sorted(bingoes[st.session_state.random_num]), "! ( PLEASE ANSWER IN ALL CAPS ) Want to find more bingoes? Use the EASY BINGO CHECKER.")

    hh = st.text_input("")
    
    if hh in bingoes:
        if sorted(hh) == sorted(bingoes[st.session_state.random_num]):
            result4 = "Correct!!"

            st.session_state.score += 1
        else:
            result4 = "Wrong answer, as bingo is not listed in our word list. As it may be missing a few, check in Zzyzzyva to be sure."
    else:
        result4 = "Wrong answer, as bingo is not listed in our word list. As it may be missing a few, check in Zzyzzyva to be sure."
    if st.button("See an answer"):
        st.write(bingoes[st.session_state.random_num])

    if st.button("Check Answer"):
        st.write(result4)

    if st.button("Next Question"):
        st.session_state.random_num = np.random.randint(0, len(bingoes))

        st.rerun()

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()
        
if st.session_state.page == "foursfrenzy":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">Fours Frenzy</div>
    """, unsafe_allow_html = True)

    # --- local storage setup for "My Word List" ---
    localS4 = LocalStorage()

    if "my_word_list" not in st.session_state:
        try:
            saved = localS4.getItem("my_four_word_list")
            st.session_state.my_word_list = json.loads(saved) if saved else []
        except Exception:
            st.session_state.my_word_list = []

    if st.button("📋 My Word List"):
        st.session_state.page = "mywordlist"
        st.rerun()

    # Paste your 4-letter words here
    fours = four_letter_words
    # -------------------------
    # Fake word generator
    # -------------------------
    
    common_consonants = "BCDFGHKLMNPRSTWY"
    vowels = "AEIOU"
    
    patterns = [
        "CVCV",
        "CVCC",
        "CVVC",
        "VCVC",
        "VCCV"
    ]
    
    
    def generate_word():
        pattern = random.choice(patterns)
    
        word = ""
    
        for letter in pattern:
            if letter == "C":
                word += random.choice(common_consonants)
            else:
                word += random.choice(vowels)
    
        return word
    
    
    
    def get_question():
    
        # 40% chance: choose a real word
        if fours and random.random() < 0.40:
            return random.choice(fours)
    
        # Otherwise generate
        return generate_word()
    
    
    
    # -------------------------
    # Session State
    # -------------------------
    
    if "word" not in st.session_state:
        st.session_state.word = get_question()
    
    if "score" not in st.session_state:
        st.session_state.score = 0
    
    if "answered" not in st.session_state:
        st.session_state.answered = False
    
    if "message" not in st.session_state:
        st.session_state.message = ""
    
    
    
    # -------------------------
    # UI
    # -------------------------
    
    st.title("4 Letter Quiz")
    
    st.write("Score:", st.session_state.score)

    st.header(st.session_state.word)
    
    
    if not st.session_state.answered:
    
        col1, col2 = st.columns(2)
    
    
        with col1:
            if st.button("Valid Word"):
    
                if st.session_state.word in fours:
                    st.session_state.score += 1
                    st.session_state.message = "Correct!"
                else:
                    st.session_state.message = "Wrong!"

                st.session_state.answered = True
                st.rerun()
    
    
        with col2:
            if st.button("Not a Word"):
    
                if st.session_state.word not in fours:
                    st.session_state.score += 1
                    st.session_state.message = "Correct!"
                else:
                    st.session_state.message = "Wrong!"

                st.session_state.answered = True
                st.rerun()
    
    
    else:
    
        if st.session_state.message == "Correct!":
            st.success(st.session_state.message)
        else:
            st.error(st.session_state.message)

        # If the word shown is an actual valid word, let the user save it
        if st.session_state.word in fours:
            if st.session_state.word in st.session_state.my_word_list:
                st.caption(f"'{st.session_state.word}' is already in your list ✅")
            else:
                if st.button(f"➕ Add '{st.session_state.word}' to My List"):
                    st.session_state.my_word_list.append(st.session_state.word)
                    localS4.setItem("my_four_word_list", json.dumps(st.session_state.my_word_list))
                    st.success(f"Added '{st.session_state.word}' to your list!")

        if st.button("Next Question"):
            st.session_state.word = get_question()
            st.session_state.answered = False
            st.session_state.message = ""
            st.rerun()
    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()

if st.session_state.page == "mywordlist":
    st.markdown("""
    <style>
        .stApp {
    background-color: #ecd9c6;
    }
    body {
    background-color: #939393;
    }
    .divvy {
    color: #dfbf9f;
    background-color: #ffffff;
    padding-top: 1vw;
    padding-bottom: 1vw;

    text-align: center;
    font-size: 3vw;
    border-radius: 1.5vw;
    margin-bottom: 1.5vw;
    }
    </style>

    <div class = "divvy">My Word List</div>
    """, unsafe_allow_html = True)

    st.write("Words you've saved, stored locally in your browser.")

    localS_list = LocalStorage()

    if "my_word_list" not in st.session_state:
        try:
            saved = localS_list.getItem("my_four_word_list")
            st.session_state.my_word_list = json.loads(saved) if saved else []
        except Exception:
            st.session_state.my_word_list = []

    st.subheader("Fours")

    if st.session_state.my_word_list:
        for w in sorted(st.session_state.my_word_list):
            col1, col2 = st.columns([4, 1])
            with col1:
                st.write(w)
            with col2:
                if st.button("❌", key="remove4_" + w):
                    st.session_state.my_word_list.remove(w)
                    localS_list.setItem("my_four_word_list", json.dumps(st.session_state.my_word_list))
                    st.rerun()

        if st.button("Clear Fours List"):
            st.session_state.my_word_list = []
            localS_list.setItem("my_four_word_list", json.dumps([]))
            st.rerun()
    else:
        st.write("Your fours list is empty! Go answer some words correctly in Fours Frenzy and add them here.")

    if st.button("Back"):
        st.session_state.page = "home"
        st.rerun()
